name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1

      - name: Setup node.js 🏡
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: '14.15.0'

      - name: Cache 📁
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-locks.lock') }}

      - name: Install 🔧
        run: |
          npm install
          npm run bootstrap

      - name: Test 🧪
        run: |
          npm test

      - name: Build 🏗️
        run: |
          npm run build

      - name: Generate docs 📃
        run: |
          npm run docgen

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: helaili/jekyll-action@57a6a260778ffcec2b3ffb312f6e515e14e9fe62 # 2.0.4
        env:
          JEKYLL_PAT: ${{ github.actor }}:${{ github.token }}
        with:
          jekyll_src: site
          target_branch: gh-pages
